"""定义 Windows W2D 连接分析静态门禁使用的增量契约。"""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WINDOWS_ROOT = ROOT / "platform" / "windows"
APP_ROOT = WINDOWS_ROOT / "MihomoMeter.Windows.App"
CORE_ROOT = WINDOWS_ROOT / "MihomoMeter.Windows.Core"

CONNECTION_REQUIRED_REPOSITORY_FILES = (
    "docs/Windows阶段W2D0实机指南.md",
    "docs/Windows阶段W2D1实机指南.md",
    "docs/Windows阶段W2D2实机指南.md",
    "docs/Windows连接分析实现契约.md",
    "scripts/windows_validation_connection_contract.py",
)

CONNECTION_REQUIRED_APP_FILES = (
    "Lifecycle/NotificationAreaMenu.Connections.cs",
    "Presentation/LiveConnectionWorkspaceModels.cs",
    "Presentation/LiveConnectionWorkspaceView.xaml",
    "Presentation/LiveConnectionWorkspaceView.xaml.cs",
    "Presentation/LiveConnectionWorkspaceViewModel.cs",
    "Presentation/LiveConnectionWorkspaceViewModel.Projection.cs",
    "Presentation/NotificationAreaConnectionController.cs",
    "Presentation/ProxyTrafficWorkspaceView.xaml",
    "Presentation/ProxyTrafficWorkspaceView.xaml.cs",
    "Infrastructure/ConnectionAnalytics/ConnectionAnalyticsLedgerLocation.cs",
    "Lifecycle/ConnectionAnalyticsTrendWindowController.cs",
    "Presentation/ConnectionAnalyticsWorkspaceModels.cs",
    "Presentation/ConnectionAnalyticsWorkspaceView.xaml",
    "Presentation/ConnectionAnalyticsWorkspaceView.xaml.cs",
    "Presentation/ConnectionAnalyticsWorkspaceViewModel.cs",
    "Presentation/ConnectionAnalyticsWorkspaceViewModel.Projection.cs",
    "Presentation/ConnectionAnalyticsTrendView.xaml",
    "Presentation/ConnectionAnalyticsTrendView.xaml.cs",
    "Presentation/ConnectionAnalyticsTrendChartView.xaml",
    "Presentation/ConnectionAnalyticsTrendChartView.xaml.cs",
    "Presentation/ConnectionAnalyticsTrendWindowViewModel.cs",
)

CONNECTION_REQUIRED_CORE_FILES = (
    "Domain/ConnectionAttributionCoverage.cs",
    "Domain/ConnectionMetadata.cs",
    "Domain/ConnectionRateAggregator.cs",
    "Application/LiveConnectionProjection.cs",
    "Infrastructure/Mihomo/ConnectionMetadataJsonConverter.cs",
    "Infrastructure/Mihomo/TolerantDateTimeOffsetJsonConverter.cs",
    "Domain/ConnectionAnalytics.cs",
    "Application/ConnectionAnalyticsRecording.cs",
    "Application/ConnectionAnalyticsState.cs",
    "Application/ConnectionAnalyticsCoordinator.cs",
    "Application/ConnectionAnalyticsCoordinator.Recording.cs",
    "Application/ConnectionAnalyticsCoordinator.Operations.cs",
    "Application/ConnectionAnalyticsWorkspaceProjection.cs",
    "Application/FaultIsolatedConnectionAnalyticsRecorder.cs",
    "Infrastructure/ConnectionAnalytics/ConnectionAnalyticsLedgerSchema.cs",
    "Infrastructure/ConnectionAnalytics/ConnectionAnalyticsLedgerPersistence.cs",
    "Infrastructure/ConnectionAnalytics/ConnectionAnalyticsLedgerPersistence.Queries.cs",
    "Infrastructure/ConnectionAnalytics/SQLiteConnectionAnalyticsLedger.cs",
    "Infrastructure/Statistics/SQLiteTrafficLedger.ProxyTraffic.cs",
)

CONNECTION_REQUIRED_TEST_FILES = (
    "ConnectionAttributionCoverageTests.cs",
    "ConnectionRateAggregatorTests.cs",
    "LiveConnectionProjectionTests.cs",
    "ConnectionAnalyticsCoordinatorTests.cs",
    "ConnectionAnalyticsProjectionTests.cs",
    "SQLiteConnectionAnalyticsLedgerTests.cs",
)

CONNECTION_REQUIRED_CODE_MARKERS = {
    ROOT / ".github/workflows/windows.yml": (
        "mihomo-meter-windows-w2d-x64-${{ github.sha }}",
        ".codex-tmp/windows-w2d-publish",
        "scripts/windows_validation_connection_contract.py",
        "docs/Windows阶段W2D0实机指南.md",
        "docs/Windows阶段W2D1实机指南.md",
        "docs/Windows阶段W2D2实机指南.md",
        "docs/Windows连接分析实现契约.md",
    ),
    ROOT / "scripts/validate_windows.ps1": (
        ".codex-tmp/windows-w2d-publish",
        "Windows 当前阶段必须复用系统 winsqlite3.dll",
    ),
    APP_ROOT / "MainWindow.xaml.cs": (
        "new RealtimeMonitoringView",
        "new TrafficStatisticsWorkspaceView",
        "new SubscriptionQuotaWorkspaceView",
        "NotificationAreaStatisticsController",
        "ShowStatisticsWorkspace",
        "ShowQuotaWorkspace",
        "WorkspaceNavigation_SelectionChanged",
        "Mihomo Meter · Windows W2D",
        "new LiveConnectionWorkspaceViewModel",
        "new ProxyTrafficWorkspaceView",
        "new ConnectionAnalyticsWorkspaceViewModel",
        "new ConnectionAnalyticsTrendWindowController",
        "ShowLiveConnectionsWorkspace",
    ),
    APP_ROOT / "Presentation/RealtimeMonitoringView.xaml": (
        "连接分析覆盖率",
        "ProxyConnectionSampleText",
        "HostnameIdentifiedText",
        "ApplicationIdentifiedText",
        "FullyIdentifiedText",
        "实时页仅展示脱敏主机名与应用名称",
    ),
    APP_ROOT / "Presentation/MainWindowViewModel.cs": (
        "snapshot.AttributionCoverage",
        "AttributionMetric",
    ),
    CORE_ROOT / "Domain/ConnectionAttributionCoverage.cs": (
        "ConnectionMetadataAvailability",
        "ConnectionAttributionCoverageTracker",
        "StringComparer.Ordinal",
        "previousAvailability.HasHostname",
        "previousAvailability.HasApplication",
    ),
    CORE_ROOT / "Domain/ConnectionMetadata.cs": (
        "ConnectionMetadata",
        "UnknownApplication",
        "UnknownHostname",
        "其他",
        "MihomoProcessMatchingMode",
    ),
    CORE_ROOT / "Domain/ConnectionRateAggregator.cs": (
        "EstablishBaseline",
        "RemoveInactiveConnections",
        "smoothingWindowCount",
        "LiveConnections",
    ),
    CORE_ROOT / "Application/LiveConnectionProjection.cs": (
        "LiveConnectionRoute",
        "LiveConnectionViewMode",
        "TopSlotCount = 5",
        "ApplicationIdentificationDiagnostic",
    ),
    CORE_ROOT / "Infrastructure/Mihomo/ConnectionMetadataJsonConverter.cs": (
        "MaximumMetadataBytes = 2_048",
        "IPAddress.TryParse",
        "Encoding.UTF8.GetByteCount",
        "JsonDocument.ParseValue",
        "OutermostApplicationBundleName",
    ),
    CORE_ROOT / "Infrastructure/Mihomo/MihomoControllerModels.cs": (
        "ConnectionMetadataJsonConverter",
        "TolerantDateTimeOffsetJsonConverter",
        "connection.Metadata",
        "connection.StartedAt",
        "find-process-mode",
    ),
    CORE_ROOT / "Application/TrafficMeasurementSession.cs": (
        "ConnectionAttributionCoverageTracker",
        "TrafficCategory.Proxy",
        "_proxyConnectionRates",
        "_directConnectionRates",
        "_attributionCoverageTracker.Reset()",
        "ConnectionAttributionDelta",
    ),
    CORE_ROOT / "Application/TrafficMonitoringStream.cs": (
        "MonitorConnectionState.Stale",
        "_policy.ReconnectAfter - _policy.StaleAfter",
        "measurement.ResetBaseline()",
        "AttributionCoverage: result.AttributionCoverage",
        "ProxyConnections: result.LiveProxyConnections",
        "DirectConnections: result.LiveDirectConnections",
        "result.ConnectionAttributionDeltas",
        "FlushPendingAsync(CancellationToken.None)",
    ),
    CORE_ROOT / "Application/TrafficMonitoringCoordinator.cs": (
        "Interlocked.Increment(ref _generation)",
        "IsCurrentSession",
        "SaveValidatedAsync",
        "backoff.Reset()",
        "BeginMonitoringAsync",
        "InterruptMonitoringAsync",
        "FaultIsolatedQuotaTrackingLifecycle",
        "TryFetchProcessMatchingModeAsync",
        "FetchProcessConfigurationAsync",
        "FaultIsolatedConnectionAnalyticsRecorder",
    ),
    APP_ROOT / "Presentation/ProxyTrafficWorkspaceView.xaml": (
        "流量统计",
        "实时连接",
        "归因历史",
        "WorkspaceContent",
    ),
    APP_ROOT / "Presentation/LiveConnectionWorkspaceView.xaml": (
        "ViewModel.ContextTitle",
        "搜索应用或域名",
        "实时速率",
        "不显示或持久化连接 ID、完整进程路径、目标 IP、端口、节点、规则和链路",
    ),
    APP_ROOT / "Presentation/LiveConnectionWorkspaceViewModel.Projection.cs": (
        ".Connections(SourceConnections, SearchText)",
        ".Groups(SourceConnections, SelectedMode.Mode, SearchText)",
        "_connections[index].Apply",
        "_groups[index].Apply",
        "ApplicationIdentificationDiagnostic.Create",
    ),
    APP_ROOT / "Presentation/NotificationAreaConnectionController.cs": (
        "LiveConnectionProjection.TopSlots",
        "Array.AsReadOnly",
        "CaptureSnapshot",
    ),
    APP_ROOT / "Lifecycle/NotificationAreaMenu.Connections.cs": (
        "TopSlotCount",
        "活动 Proxy Top 5",
        "活动直连 Top 5",
        "OpenLiveConnections",
    ),
    APP_ROOT / "Infrastructure/ConnectionAnalytics/ConnectionAnalyticsLedgerLocation.cs": (
        "LocalApplicationData",
        "connection-analytics.sqlite3",
    ),
    APP_ROOT / "Infrastructure/WindowsAppServices.cs": (
        "AllowAutoRedirect = false",
        "UseProxy = false",
        "SQLiteTrafficLedger",
        "TrafficStatisticsCoordinator",
        "SQLiteQuotaLedger",
        "QuotaTrackingCoordinator",
        "YamlClashProfileCatalogReader",
        "MihomoActiveQuotaQueryClient",
        "SQLiteConnectionAnalyticsLedger",
        "ConnectionAnalyticsCoordinator",
        "connectionAnalyticsHistory: connectionAnalytics",
        "connectionAnalyticsRecorder: connectionAnalytics",
        "await ConnectionAnalytics.DisposeAsync()",
    ),
    CORE_ROOT / "Domain/ConnectionAnalytics.cs": (
        "RecentDayCount = 30",
        "ConnectionAnalyticsRecordingCoverage",
    ),
    CORE_ROOT / "Application/ConnectionAnalyticsCoordinator.cs": (
        "TimeSpan.FromSeconds(10)",
        "DefaultMaximumPairCountPerDay = 5_000",
        "SetHistoryEnabledAsync",
        "SelectDayAsync",
    ),
    CORE_ROOT / "Application/ConnectionAnalyticsCoordinator.Recording.cs": (
        "ConnectionAnalyticsCalendar.LocalDay",
        "FlushPendingCoreAsync",
        "FlushPendingForTrendAsync",
        "ScheduleFlushLocked",
    ),
    CORE_ROOT / "Infrastructure/ConnectionAnalytics/ConnectionAnalyticsLedgerSchema.cs": (
        "connection_analytics_settings",
        "history_enabled",
        "connection_daily_attribution",
        "application_name",
        "hostname",
    ),
    CORE_ROOT / "Infrastructure/ConnectionAnalytics/SQLiteConnectionAnalyticsLedger.cs": (
        "maximumPairCount - 1",
        "ConnectionAttributionLabel.Overflow",
        "RecentLocalDays",
        "PruneIfNeeded",
    ),
    CORE_ROOT / "Application/TrafficStatisticsCoordinator.cs": (
        "_operationGate",
        "StartIntervalAsync",
        "TryInterruptAfterStatisticsFailureAsync",
        "ClearHistoryAsync",
        "核心流量统计已清空，但连接归因历史未能清空",
    ),
    APP_ROOT / "Presentation/ConnectionAnalyticsWorkspaceView.xaml": (
        "记录日聚合",
        "应用榜",
        "域名榜",
        "归因记录覆盖",
        "清空归因历史",
    ),
    APP_ROOT / "Presentation/ConnectionAnalyticsTrendWindowViewModel.cs": (
        "_requestGeneration",
        "CancelRequest",
        "keepsPreviousResult",
    ),
    APP_ROOT / "Presentation/ConnectionAnalyticsTrendChartView.xaml": (
        'Height="48"',
        "PointerMoved",
        "PointDetailText",
    ),
}
